- debug: var={{ item }}
  when: debug is defined
  with_items:
      - config
      - crb_db_user
      - crb_db_name
      - gnupg_home_dir
      - virtualenv
  tags:
    - always

- include: install_testtools.yml
  tags:
    - env

- include: setup_cerebrum.yml
  tags:
    - env

- include: setup_database.yml
  tags:
    - env

- include: setup_gpg.yml
  tags:
    - env

- include: run_pytest_tests.yml
  vars:
    coverage_report: "{{ config | default('default')  }}_coverage.xml"
    xunit_report: "{{ config | default('default') }}_xunit.xml"
  tags:
    - test
