- name: move extra files to host
  copy:
      src: "{{ item }}"
      dest: "{{ item | tmpfile }}"
  with_first_found:
    - files:
        - 'extra_db_files.txt'
      paths:
        - files/{{config}}
        - files/
  register: _extra_files

- name: create cerebrum schema with makedb
  makedb:
      virtualenv: "{{ virtualenv }}"
      extra_files_src: "{{ _extra_files | dest }}"
