- name: locate virtualenv site-packages
  virtualenv_info:
      env: "{{ virtualenv }}"
      info: site
  register: _virtualenv_info

- name: place cerebrum_path module
  template:
      src: "cerebrum_path.j2"
      dest: "{{ _virtualenv_info.site }}/cerebrum_path.py"
      validate: "{{ virtualenv }}/bin/python -B %s"

- name: place cereconf
  template:
      src: "{{ item }}"
      dest: "{{ virtualenv }}/etc/cerebrum/cereconf.py"
      validate: "{{ virtualenv }}/bin/python -B %s"
  with_file_overload:
    - base: 'templates'
    - file: 'cereconf.j2'
    - alt: '{{ config | default(None) }}'

# TODO: ldapconf, other configs?

- name: place log config
  template:
      src: "{{ item }}"
      dest: "{{ virtualenv }}/etc/cerebrum/logging.ini"
      validate: "python -c \"import ConfigParser;c=ConfigParser.ConfigParser();assert len(c.read(['%s', ]))==1\""
  with_file_overload:
    - base: 'templates'
    - file: 'logging.j2'
    - alt: '{{ config | default(None) }}'

- name: create dummy file for database password
  template:
      src: "{{ item }}"
      dest: "{{ virtualenv }}/etc/cerebrum/passwd-{{ crb_db_user }}@{{ crb_db_name }}@localhost"
      validate: "grep {{crb_db_user}} %s"
  with_file_overload:
    - base: 'templates'
    - file: 'passwd.j2'
    - alt: '{{ config | default(None) }}'

- name: place adconf
  template:
      src: "{{ item }}"
      dest: "{{ virtualenv }}/etc/cerebrum/adconf.py"
      validate: "{{ virtualenv }}/bin/python -B %s"
  with_file_overload:
    - base: 'templates'
    - file: 'adconf.j2'
    - alt: '{{ config | default(None) }}'
    - skip: yes
