# Set up host as a Cerebrum test machine.
#
# We'll install the neccessary packages, set up postgres users and start the
# postgres service.
#
# NOTE: For any of these tasks to do changes, you'll need to run the playbook
# with:
#
#   ansible-playbook <file> --ask-sudo-pass

#
# Install missing packages with yum.
#
- name: install python environment requirements
  action: yum state=present name={{ item }}
  with_items:
    - python
    - python-devel
    - python-virtualenv
    - postgresql-devel
  sudo: yes

- name: Install dependencies to build lxml  # Used in Ad2
  action: yum state=present name={{ item }}
  with_items:
   - libxml2
   - libxml2-devel
   - libxslt
   - libxslt-devel
  sudo: yes

- name: Install dependencies to build pygpgme  # Used in Ad2
  action: yum state=present name={{ item }}
  with_items:
   - gpgme
   - gpgme-devel
  sudo: yes
